name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd ./gee && cargo build --verbose

      - name: Run tests
        run: cd ./gee && cargo test --verbose
